# Generated by Django 3.1 on 2023-05-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_coverphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverphoto',
            name='image',
            field=models.ImageField(upload_to='photos/cover_photos'),
        ),
    ]
